apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data-pvc
  namespace: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
